name: docs-to-pdf

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/convert-to-pdf.yml'

jobs:
  build-pdf:
    name: Build & Commit PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate combined PDF
        run: |
          cd docs
          pandoc pages/*.md -o user-guide.pdf --toc --pdf-engine=xelatex --resource-path=.:images --fail-if-warnings


      - name: Commit PDF to repository
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/user-guide.pdf
          git commit -m "📄 Auto-generate user-guide.pdf" || echo "No changes to commit"
          git push
