name: Convert Markdown to PDF

on:
  push:
    branches: [main]

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔍 Debug - Check repository structure
        run: |
          echo "=== Repository root contents ==="
          ls -la
          echo -e "\n=== Looking for markdown files ==="
          find . -name "*.md" -o -name "*.markdown" | head -20
          echo -e "\n=== Check docs directory ==="
          ls -la docs/ || echo "docs/ directory doesn't exist"
          echo -e "\n=== Check _pages directory ==="
          ls -la docs/_pages/ || echo "docs/_pages/ directory doesn't exist"
          echo -e "\n=== Count of .md files in different locations ==="
          find . -name "*.md" | wc -l
          find docs/ -name "*.md" 2>/dev/null | wc -l || echo "No docs/ directory"
          find docs/_pages/ -name "*.md" 2>/dev/null | wc -l || echo "No docs/_pages/ directory"

      - name: 🧹 Create PDF directory
        run: |
          mkdir -p docs/_pages/pdf
          rm -f docs/_pages/pdf/*.pdf

      - name: 📄 Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_path: docs/_pages  # Use input_path instead of input_dir
          output_dir: docs/_pages/pdf
          images_dir: docs/_pages  # Directory containing any images referenced in markdown
          build_html: false
          build_pdf: true

      - name: 📋 List generated PDFs
        run: |
          echo "Generated PDF files:"
          ls -lah docs/_pages/pdf/
          echo -e "\nPDF count:"
          find docs/_pages/pdf -name "*.pdf" | wc -l

      - name: 🚀 Commit and push PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if we have any PDFs to commit
          if ls docs/_pages/pdf/*.pdf 1> /dev/null 2>&1; then
            git add docs/_pages/pdf/*.pdf
            git status
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Generate PDFs from markdown files [skip ci]"
              git push origin main
            fi
          else
            echo "No PDF files found to commit"
          fi