name: Convert Markdown to PDF

on:
  push:
    branches: [main]

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🧹 Create PDF directory
        run: |
          mkdir -p docs/pages/pdf
          rm -f docs/pages/pdf/*.pdf

      - name: 📄 Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs/pages  # Adjust this to where your .md files are
          output_dir: docs/pages/pdf
          images_dir: docs/pages  # Directory containing any images referenced in markdown
          build_html: false

      - name: 📋 List generated PDFs
        run: |
          echo "Generated PDF files:"
          ls -lah docs/pages/pdf/

      - name: 🚀 Commit and push PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pages/pdf/*.pdf || true
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate PDFs from markdown files [skip ci]"
            git push origin main
          fi