name: docs-to-pdf

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/convert-to-pdf.yml'

jobs:
  build-pdf:
    name: Build & Commit PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Generate one PDF per Markdown file
        run: |
          for file in docs/pages/*.md; do
            filename=$(basename "$file" .md)
            pandoc "$file" \
              --lua-filter=ignore-images.lua \
              --pdf-engine=xelatex \
              --toc \
              -o "docs/pages/${filename}.pdf"
          done


      - name: Commit generated PDFs
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/pages/*.pdf
          git commit -m "📄 Auto-generate per-page PDFs" || echo "🤖 No PDF changes to commit"
          git push
