name: docs-to-pdf

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/convert-to-pdf.yml'

jobs:
  build-pdf:
    name: Build & Commit PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF (ignoring images)
        run: |
          pandoc docs/*.md \
            --lua-filter=ignore-images.lua \
            --pdf-engine=xelatex \
            --toc \
            -o user-guide.pdf

      - name: Commit PDF to repository
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/user-guide.pdf
          git commit -m "📄 Auto-generate user-guide.pdf" || echo "No changes to commit"
          git push
