name: Generate PDFs from Jekyll HTML

on:
  push:
    branches: [main] # Change if your default branch is different

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build Jekyll site
        run: jekyll build

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Clean old PDFs
        run: |
          mkdir -p docs/pages/pdf
          rm -f docs/pages/pdf/*.pdf

      - name: Convert built HTML to PDFs
        run: |
          mkdir -p docs/pages/pdf
          shopt -s nullglob
          for html in _site/docs/pages/md/*/index.html; do
            dir="$(dirname "$html")"
            page="$(basename "$dir")"
            echo "Converting $html → docs/pages/pdf/${page}.pdf"
            wkhtmltopdf --enable-local-file-access "$html" "docs/pages/pdf/${page}.pdf"
          done

      - name: Commit and push generated PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pages/pdf
          git commit -m "Update PDFs from built HTML [skip ci]" || echo "No changes to commit"
          git push origin main
